### ISSUE TITLE
wtf is a mothership

### ISSUE THREAD

**Issue by timoxley** [thlorenz/mothership#1]
wat

**Comment by thlorenz** [comment]
wtf is so hard to understand about this, it's the :package:  that's relevant to us for the given context **:P**

I'm using it in order to find the `package.json` that contains the browserify transform config of the transform that got applied to a specific file.

:ship:

**Comment by timoxley** [comment]
Readme makes sense now. Cool. :+1:

**Comment by thlorenz** [comment]
:) wasn't sure if you were serious or not.
Possibly you got to it before I properly implemented and documented things. I usually create a repo right away with Status indicating that it's not finished.

Happy you know what mothership is now.
